trial_name: dredge15min
description: "15 mins to see if works"

ks_batch_size: 30000
ks_extra_settings: {nblocks: 0}
n_jobs: 12

pipeline:
  - step: slice_time
    start_time_s: 0
    duration_s: 900
  - step: highpass_filter
    ftype: bessel
  - step: phase_shift
  - step: remove_artifacts
    threshold: 3900
    ms_before: 50
    ms_after: 50
    mode: linear
  - step: split_shank
  - step: correct_motion
    preset: dredge
    estimate_motion_kwargs:
      win_step_um: 60
      win_scale_um: 60
      win_margin_um: -30
  - step: global_cmr
    operator: median
  - step: detect_interpolate_bad_channels
    methods: [coherence+psd, mad]
  - step: local_cmr
  - step: bandpass_filter
    freq_min: 300.0
    freq_max: 7500.0

