trial_name: dredge_bin_s
description: "changing dredge motion correction window to 150 um and bin_s to 4.0"

ks_batch_size: 30000
ks_extra_settings: {nblocks: 0}
n_jobs: 12

pipeline:
  - step: slice_time
    start_time_s: 0
    duration_s: 3600
  - step: highpass_filter
    ftype: bessel
  - step: phase_shift
  - step: remove_artifacts
    threshold: 1500
    ms_before: 50
    ms_after: 50
    mode: linear
  - step: split_shank
  - step: correct_motion
    preset: dredge
    estimate_motion_kwargs:
      win_step_um: 150
      win_scale_um: 150
      win_margin_um: -75
      bin_s: 4.0
  - step: global_cmr
    operator: median
  - step: detect_interpolate_bad_channels
    methods: [coherence+psd, mad]
  - step: local_cmr
  - step: bandpass_filter
    freq_min: 300.0
    freq_max: 7500.0

